"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-07 12:19:31.652173

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted by hand: autogenerate rendered every enum CHECK constraint twice (once named after
    # the enum, once by the naming convention). Only the convention-named constraints are kept and
    # sa.Enum(create_constraint=False) stops the type from adding a third one.
    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "needs_clarification",
                "completed",
                "failed",
                name="recommendation_status",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("locale", sa.String(length=5), nullable=False),
        sa.Column(
            "input_mode",
            sa.Enum(
                "text",
                "voice",
                name="input_mode",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("clarification_question", sa.Text(), nullable=True),
        sa.Column("clarification_answer", sa.Text(), nullable=True),
        sa.Column("need_profile", sa.JSON(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("artist", sa.String(length=500), nullable=True),
        sa.Column("album_art_url", sa.String(length=1000), nullable=True),
        sa.Column("spotify_track_id", sa.String(length=64), nullable=True),
        sa.Column("spotify_url", sa.String(length=1000), nullable=True),
        sa.Column("spotify_verified", sa.Boolean(), nullable=False),
        sa.Column("youtube_url", sa.String(length=1000), nullable=True),
        sa.Column("youtube_verified", sa.Boolean(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("need_summary", sa.Text(), nullable=True),
        sa.Column("models_used", sa.JSON(), nullable=True),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "input_mode IN ('text', 'voice')", name=op.f("ck_recommendations_input_mode")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'needs_clarification', 'completed', 'failed')",
            name=op.f("ck_recommendations_recommendation_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_spotify_track_id"), ["spotify_track_id"], unique=False
        )

    op.create_table(
        "track_link_cache",
        sa.Column("normalized_key", sa.String(length=1000), nullable=False),
        sa.Column("spotify_track_id", sa.String(length=64), nullable=True),
        sa.Column("spotify_url", sa.String(length=1000), nullable=True),
        sa.Column("spotify_title", sa.String(length=500), nullable=True),
        sa.Column("spotify_artist", sa.String(length=500), nullable=True),
        sa.Column("album_art_url", sa.String(length=1000), nullable=True),
        sa.Column("spotify_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("youtube_video_id", sa.String(length=32), nullable=True),
        sa.Column("youtube_fetched_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("normalized_key", name=op.f("pk_track_link_cache")),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("synced_to_langsmith", sa.Boolean(), nullable=False),
        sa.CheckConstraint("score IN (0, 1)", name=op.f("ck_feedback_score_binary")),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_feedback_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feedback_recommendation_id"), ["recommendation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_recommendation_id"))

    op.drop_table("feedback")
    op.drop_table("track_link_cache")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_spotify_track_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_created_at"))

    op.drop_table("recommendations")
    # ### end Alembic commands ###
